- job_name: 'node_exporter_metrics'
  scrape_interval: 5s
  static_configs:
    - targets: ['192.168.88.10:9100']

- job_name: 'node_exporter_lb1haproxy'
  scrape_interval: 5s
  static_configs:
    - targets: ['192.168.88.51:9100']
    
- job_name: 'node_exporter_lb2haproxy'
  scrape_interval: 5s
  static_configs:
    - targets: ['192.168.88.52:9100']

- job_name: 'Mikrotik'
  scrape_interval: 5s
  static_configs:
    - targets: 
      - 192.168.88.1
  metrics_path: /snmp
  params:
    module: [if_mib]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 10.104.232.153:9116
