apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-nfs-pvc-myweb
  namespace: myweb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 1Gi
